name: Publish to AUR

on:
  release:
    types: [published]

jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate PKGBUILD
        run: |
          # Extract version from tag (remove 'v' prefix if present)
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          
          # Download the source tarball to calculate SHA256
          wget "https://github.com/${{ github.repository }}/archive/v${VERSION}.tar.gz" -O "eleviewr-${VERSION}.tar.gz"
          SHA256=$(sha256sum "eleviewr-${VERSION}.tar.gz" | cut -d' ' -f1)
          
          # Update PKGBUILD with new version and SHA256
          sed -i "s/pkgver=.*/pkgver=${VERSION}/" PKGBUILD
          sed -i "s/sha256sums=.*/sha256sums=('${SHA256}')/" PKGBUILD
          
          # Generate .SRCINFO
          docker run --rm -v "$PWD:/pkg" archlinux:latest bash -c "
            pacman -Syu --noconfirm base-devel
            useradd -m builder
            chown -R builder:builder /pkg
            cd /pkg
            sudo -u builder makepkg --printsrcinfo > .SRCINFO
          "

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: eleviewr
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update to v${{ github.ref_name }}
          allow_empty_commits: false