name: Tests and Linting

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwayland-dev libxkbcommon-dev
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
      
      - name: Run tests
        working-directory: ./
        run: cargo test --verbose
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      
      - name: Rust cache
        uses: swatinem/rust-cache@v2
      
      - name: Run rustfmt
        working-directory: ./
        run: cargo fmt --all -- --check
      
      - name: Run clippy
        working-directory: ./
        run: cargo clippy -- -D warnings